# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 3.2.2
core_version = 3.2.1
releaseType = BETA
changelog = Update to 26.3


maven_group = de.erdbeerbaerlp.dcintegration.architectury
archives_name = dcintegration
enabled_platforms = fabric

# Minecraft properties
minecraft_version = 26.3

# Dependencies
fabric_loader_version = 0.19.5
fabric_api_version = 0.160.5+26.3
neoforge_version = 26.2.0.6-beta

# Fabric Dependencies
fabric_permissions_api = 0.7.0
placeholder_api = 3.2.0+26.3
styled_chat = 2.14.0+26.3
vanish = 1.6.14+26.2

# NeoForge Dependencies
vanishmod = iVEuBaPo
#TODO No 26.2 ver yet